exp_name: alohasim_0304_small_speed2
batch_size: 16
lr: 1e-4
multi_gpu: [0]
log_every_steps: 1000
save_every_steps: 5000
fig_every_steps: 1000
num_train_steps: 80000
s1_till_steps: 10000
s2_till_steps: 40000
s1_strategy: mean
num_queries: 32
speed_range: [0.8, 1.5]
speed_step: 0.1
group_loss_window: 1
action_overcollect_ratio: 1
syn_optimize_ratio: True
constrain_speed_via_ratio_head: True
constrain_from_ratio_coef: 0.5
constrain_start_step: 20000
constrain_coef_linear_up: True
constrain_other_coef_linear_down: False
optimize_target: action
action_recon_coef: 0.2
noise_init_varying_multispeed: same
criterion_type: action
step_loss_type: log_denominator
step_loss_ratio: 1.2
