bc_dataset:
  _target_: read_data.alohareal_ddp.BCDataset
  path: ${oc.env:autospeed_DATA_ROOT,./data/aloha_datasets}
  tasks: ${suite.task.tasks}
  num_queries: ${agent.num_queries}
  new_loss_args: ${agent.new_loss_args} 
  action_overcollect_ratio: 2
  stats_path: ???
  img_size: ${suite.img_size}
  proprio_dim: ${suite.proprio_dim}
  group_loss_window: ${agent.group_loss_window}
  debug: ${dataloader_debug}
