exp_name: metaworld_exp0303_speed
batch_size: 64
lr: 1e-4
multi_gpu: [0,1]
log_every_steps: 1000
save_every_steps: 5000
fig_every_steps: 1000
num_train_steps: 400000
s1_till_steps: 50000
s2_till_steps: 150000
s1_strategy: mean
num_queries: 16
speed_range: [1, 2]
speed_step: 0.2
group_loss_window: 1
syn_optimize_ratio: True
constrain_speed_via_ratio_head: True
constrain_from_ratio_coef: 0.5
constrain_start_step: 100000
constrain_coef_linear_up: True
constrain_other_coef_linear_down: False
optimize_target: action
action_recon_coef: 0.2
noise_init_varying_multispeed: same
criterion_type: action
step_loss_type: log_denominator
step_loss_ratio: 1.3
